{{- if .Values.kubeconfigSecretName }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-ui-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-ui-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs: ["get"]

{{- end }}
