{{- if .Values.kubeconfigSecretName }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kube-ui-server.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-ui-server.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 3
  template:
    spec:
      {{- include "appscode.imagePullSecrets" $ | nindent 6 }}
      serviceAccountName: {{ include "kube-ui-server.serviceAccountName" . }}
      automountServiceAccountToken: true
      containers:
      - name: kubectl
        image: {{ include "image.registry" $ }}/kubectl:1.23
        workingDir: /var/run/secrets/ocm
        command:
          - sh
          - -c
          - |
              sleep 2; \
              SVC_IP=$(kubectl get service -n {{ .Release.Namespace }} {{ include "kube-ui-server.fullname" . }} -o=jsonpath='{.spec.clusterIP}'); \
              kubectl --kubeconfig=auth/kubeconfig create namespace {{ .Release.Namespace }} || true; \
              kubectl --kubeconfig=auth/kubeconfig delete service -n {{ .Release.Namespace }} {{ include "kube-ui-server.fullname" . }} || true; \
              kubectl --kubeconfig=auth/kubeconfig delete endpoints -n {{ .Release.Namespace }} {{ include "kube-ui-server.fullname" . }} || true; \
              kubectl --kubeconfig=auth/kubeconfig apply -f - <<EOF
              apiVersion: v1
              kind: Service
              metadata:
                name: {{ include "kube-ui-server.fullname" . }}
                namespace: {{ .Release.Namespace }}
              spec:
                clusterIP: $SVC_IP
                ports:
                - name: api
                  port: 443
                  protocol: TCP
                  targetPort: 8443
                sessionAffinity: None
                type: ClusterIP
              ---
              apiVersion: v1
              kind: Endpoints
              metadata:
                name: {{ include "kube-ui-server.fullname" . }}
                namespace: {{ .Release.Namespace }}
              subsets:
              - addresses:
                - ip: $SVC_IP
                ports:
                - name: api
                  port: 8443
                  protocol: TCP
              EOF
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
        - mountPath: /var/run/secrets/ocm/auth
          name: ocm-auth
      volumes:
      - name: ocm-auth
        secret:
          defaultMode: 420
          secretName: {{ .Values.kubeconfigSecretName }}
      restartPolicy: Never
{{- end }}




