{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- if .Capabilities.APIVersions.Has "storage.k8s.io/v1/CSIDriver" }}
apiVersion: storage.k8s.io/v1
{{- else }}
apiVersion: storage.k8s.io/v1beta1
{{- end }}
kind: CSIDriver
metadata:
  name: {{ .Values.app.driver.name }}
  labels:
    {{- include "cert-manager-csi-driver-cacerts.labels" . | nindent 4 }}
spec:
  attachRequired: false
  # need pod namespace
  podInfoOnMount: true
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1855-csi-driver-service-account-token/README.md#api-changes
  # reconcilerLoopSleepPeriod: 0.1s
  # requiresRepublish: true
  volumeLifecycleModes:
  - Ephemeral
{{- if and (ge $major 1) (ge $minor 20) }}
  fsGroupPolicy: File
{{- end }}
