apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: placementpolicies.apps.k8s.appscode.com
spec:
  group: apps.k8s.appscode.com
  names:
    kind: PlacementPolicy
    listKind: PlacementPolicyList
    plural: placementpolicies
    singular: placementpolicy
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              nodeAffinity:
                items:
                  properties:
                    domains:
                      items:
                        properties:
                          replicas:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - replicas
                        - values
                        type: object
                      type: array
                    topologyKey:
                      type: string
                    whenUnsatisfiable:
                      type: string
                  required:
                  - domains
                  - topologyKey
                  - whenUnsatisfiable
                  type: object
                type: array
              nodeSpreadConstraint:
                properties:
                  maxSkew:
                    format: int32
                    type: integer
                  whenUnsatisfiable:
                    type: string
                required:
                - maxSkew
                - whenUnsatisfiable
                type: object
              zoneSpreadConstraint:
                properties:
                  maxSkew:
                    format: int32
                    type: integer
                  whenUnsatisfiable:
                    type: string
                required:
                - maxSkew
                - whenUnsatisfiable
                type: object
            type: object
        type: object
    served: true
    storage: true
