apiVersion: v1
description: Falco UI Server by AppsCode
name: falco-ui-server
version: v2024.5.17
appVersion: v0.0.4
home: https://github.com/kubeops/falco-ui-server
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kubeops/falco-ui-server
maintainers:
- name: appscode
  email: support@appscode.com
