apiVersion: v1
description: Kubernetes Panopticon by AppsCode
name: panopticon
version: v2024.11.8
appVersion: v0.0.16
home: https://github.com/kubeops/panopticon
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kubeops/panopticon
maintainers:
- name: appscode
  email: support@appscode.com
