project:
  name: Operator Shard Manager by AppsCode
  shortName: Operator Shard Manager
  url: https://github.com/appscode-cloud
  description: Operator Shard Manager
  app: a Operator Shard Manager
repository:
  url: https://charts.appscode.com/stable
  name: appscode
chart:
  name: operator-shard-manager
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: operator-shard-manager
  namespace: ace
