apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:ace:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - appreleases
  verbs: ["create", "delete", "deletecollection", "patch", "update"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appscode:ace:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - node.k8s.appscode.com
  resources:
  - nodetopologies
  verbs: ["get", "list", "watch"]
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - appreleases
  verbs: ["get", "list", "watch"]
