apiVersion: v1
description: Petset Operator by AppsCode
name: petset
version: v2024.6.3
appVersion: v0.0.6
home: https://kubedb.com/
icon: https://cdn.appscode.com/images/products/stash/petset-icon.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
