apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scanner.fullname" . }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cves.scanner.appscode.com
  resources:
  - "*"
  verbs: ["*"]
# Get cluster id
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get"]
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch", "create", "patch", "delete"]
