{{- if .Values.cacher.enable }}

{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{ else }}
apiVersion: batch/v1beta1
{{ end -}}
kind: CronJob
metadata:
  name: {{ include "scanner.fullname" . }}-trivydb-cacher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          {{- include "appscode.imagePullSecrets" . | nindent 10 }}
          serviceAccountName: {{ include "scanner.serviceAccountName" . }}
          containers:
          - name: cacher
            securityContext:
              {{- toYaml .Values.cacher.securityContext | nindent 14 }}
            image: {{ include "cacher.registry" . }}/{{ .Values.cacher.repository }}:{{ .Values.cacher.tag }}
            imagePullPolicy: {{ .Values.imagePullPolicy  }}
            command:
            - /scripts/update-trivydb.sh
            resources:
              {{- toYaml .Values.cacher.resources | nindent 14 }}
          restartPolicy: Never
  schedule: {{ .Values.cacher.schedule | quote }}
  successfulJobsHistoryLimit: 4
  suspend: false
{{- end }}
