{{- $caCrt := "" }}
{{- $serverCrt := "" }}
{{- $serverKey := "" }}
{{- if .Values.etcd.servingCerts.generate }}
{{- $ca := genCA "etcd-ca" 3650 }}
{{- $cn := include "scanner.fullname" . -}}
{{- $server := genSignedCert $cn (list "127.0.0.1") (list "localhost") 3650 $ca }}
{{- $caCrt =  b64enc $ca.Cert }}
{{- $serverCrt = b64enc $server.Cert }}
{{- $serverKey = b64enc $server.Key }}
{{- else }}
{{- $caCrt = required "Required when etcd.servingCerts.generate is false" .Values.etcd.servingCerts.caCrt }}
{{- $serverCrt = required "Required when etcd.servingCerts.generate is false" .Values.etcd.servingCerts.serverCrt }}
{{- $serverKey = required "Required when etcd.servingCerts.generate is false" .Values.etcd.servingCerts.serverKey }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scanner.fullname" . }}-etcd-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $caCrt }}
  tls.crt: {{ $serverCrt }}
  tls.key: {{ $serverKey }}
