{{- with .Values.licenses }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scanner.fullname" . }}-licenses
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
