apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scanner.fullname" . }}-trivydb-reader
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
rules:
- nonResourceURLs: ["/files/db.tar.gz"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scanner.fullname" . }}-trivydb-reader
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "scanner.fullname" . }}-trivydb-reader
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
