apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: baseline
  name: {{ .Values.workspace.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scanner.fullname" . }}
  namespace: {{ .Values.workspace.namespace }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "scanner.fullname" . }}
  namespace: {{ .Values.workspace.namespace }}
  labels:
    {{- include "scanner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "scanner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
