{{- if not .Values.kubeconfigSecretName }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-ui-server.fullname" . }}
  labels:
    {{- include "kube-ui-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - core.k8s.appscode.com
  - cost.k8s.appscode.com
  - identity.k8s.appscode.com
  - management.k8s.appscode.com
  - meta.k8s.appscode.com
  - offline.licenses.appscode.com
  - policy.k8s.appscode.com
  - reports.scanner.appscode.com
  - ui.k8s.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmrepositories
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["create", "update", "patch", "get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["deletecollection"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  # create used for raw REST query
  - create
  - get
  - list
  - watch
# ocm cluster claim
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clusterclaims
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# impersonate user for grafana dashboard calls
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]
# Can set "Impersonate-Extra-ace.appscode.com/org-id" header and the "Impersonate-Uid" header.
- apiGroups: ["authentication.k8s.io"]
  resources: ["userextras/ace.appscode.com/org-id", "uids"]
  verbs: ["impersonate"]
- nonResourceURLs:
  - '*'
  verbs:
  - get
{{- end }}
