{{- if not .Values.kubeconfigSecretName }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:kube-ui-server:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - core.k8s.appscode.com
  - cost.k8s.appscode.com
  - identity.k8s.appscode.com
  - management.k8s.appscode.com
  - meta.k8s.appscode.com
  - offline.licenses.appscode.com
  - policy.k8s.appscode.com
  - reports.scanner.appscode.com
  - ui.k8s.appscode.com
  resources:
  - "*"
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:kube-ui-server:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - identity.k8s.appscode.com
  resources:
  - inboxtokenrequests
  - selfsubjectnamespaceaccessreviews
  verbs: ["create"]
- apiGroups:
  - identity.k8s.appscode.com
  resources:
  - clusteridentities
  - siteinfos
  verbs: ["get", "list"]
- apiGroups:
  - core.k8s.appscode.com
  resources:
  - genericresources
  - genericresourceservices
  - podviews
  - projects
  - resourcesummaries
  verbs: ["get", "list"]
- apiGroups:
  - management.k8s.appscode.com
  resources:
  - projectquotas
  verbs: ["get", "list"]
- apiGroups:
  - ui.k8s.appscode.com
  resources:
  - features
  - featuresets
  - resourcedashboards
  - resourceeditors
  verbs: ["get", "list"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - chartpresetqueries
  - clusterstatuses
  - renderdashboards
  - rendermenus
  - renderrawgraphs
  - renders
  - resourcecalculators
  - resourcegraphs
  verbs: ["create"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - menus
  - resourceblockdefinitions
  - resourcedescriptors
  - resourceeditors
  - resourcelayouts
  - resourceoutlines
  - resourcetabledefinitions
  - usermenus
  - gatewayinfos
  verbs: ["get", "list"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - menus/available
  - usermenus/available
  verbs: ["get"]
- apiGroups:
  - meta.k8s.appscode.com
  resources:
  - usermenus
  verbs: ["*"]

---

# Grant logged in users permission on cluster scoped resources required for cluster-ui

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appscode:kube-ui-server:view
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appscode:kube-ui-server:view
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io

{{- end }}
