apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falco-ui-server.fullname" . }}-receiver
  labels:
    {{- include "falco-ui-server.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /falcoevents
  verbs: ["post"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "falco-ui-server.fullname" . }}-receiver
  labels:
    {{- include "falco-ui-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "falco-ui-server.fullname" . }}-receiver
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous
