{{- if .Values.helmRepositories.create }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bytebuilders-ui
  namespace: {{ .Release.Namespace }}
spec:
  type: oci
  interval: 30m
  url: oci://r.byte.builders/charts/
{{- end }}
