{{- range $old, $nu := .Values.gke.copyStorageClasses }}

{{ $oldObj := lookup "storage.k8s.io/v1" "StorageClass" "" $old }}

{{- if $oldObj }}

{{- $_ := set $oldObj "metadata" (dict "name" $nu.name) }}
{{- $_ := set $oldObj "mountOptions" ( list "noatime") }}

{{- $params := dict }}
{{- if $oldObj.parameters }}
{{- $params = $oldObj.parameters }}
{{- end }}

{{- if $nu.fsType  }}
{{- $_ := set $params "csi.storage.k8s.io/fstype" $nu.fsType }}
{{- end }}

{{- $_ := set $oldObj "parameters" $params }}

{{ toYaml $oldObj }}

{{- end }}
{{- end }}
