{{- range $old, $nu := .Values.gke.copyStorageClasses }}

{{ $oldObj := lookup "storage.k8s.io/v1" "StorageClass" "" $old }}

{{- if $oldObj }}

{{- $_ := set $oldObj "metadata" (dict "name" $nu) }}
{{- $_ := set $oldObj "mountOptions" ( list "noatime") }}

{{- $_ := set $oldObj "parameters" (merge $oldObj.parameters (dict "csi.storage.k8s.io/fstype" "xfs")) }}

{{ toYaml $oldObj }}

{{- end }}
{{- end }}
