{{- if not .Values.ocm }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extra:ui:viewer
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - "appreleases"
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extra:ui:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - "appreleases"
  verbs: ["create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extra:ui:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - "appreleases"
  verbs: ["deletecollection"]
{{ end }}