apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceoutlinefilters.ui.k8s.appscode.com
spec:
  group: ui.k8s.appscode.com
  names:
    kind: ResourceOutlineFilter
    listKind: ResourceOutlineFilterList
    plural: resourceoutlinefilters
    singular: resourceoutlinefilter
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              actions:
                items:
                  properties:
                    items:
                      additionalProperties:
                        type: boolean
                      type: object
                    name:
                      type: string
                    show:
                      type: boolean
                  required:
                  - name
                  - show
                  type: object
                type: array
              header:
                type: boolean
              pages:
                items:
                  properties:
                    name:
                      type: string
                    sections:
                      items:
                        properties:
                          blocks:
                            additionalProperties:
                              type: boolean
                            type: object
                          info:
                            additionalProperties:
                              type: boolean
                            type: object
                          insight:
                            type: boolean
                          name:
                            type: string
                          show:
                            type: boolean
                        required:
                        - info
                        - insight
                        - show
                        type: object
                      type: array
                    show:
                      type: boolean
                  required:
                  - name
                  - show
                  type: object
                type: array
              resource:
                properties:
                  group:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  scope:
                    type: string
                  version:
                    type: string
                required:
                - group
                type: object
              tabBar:
                type: boolean
            required:
            - header
            - resource
            - tabBar
            type: object
        type: object
    served: true
    storage: true
