apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator-shard-manager.fullname" . }}-stats
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator-shard-manager.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "operator-shard-manager.labels" . | nindent 4 }}
