{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.supervisor.appscode.com
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
  - name: maintenancewindows.validators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: default
        name: kubernetes
        path: /apis/maintenancewindows.validators.supervisor.appscode.com/v1alpha1/maintenancewindows
      caBundle: {{ b64enc .Values.apiserver.ca }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - supervisor.appscode.com
        apiVersions:
          - "*"
        resources:
          - maintenancewindows
    admissionReviewVersions: ["v1beta1"]
    failurePolicy: Fail
    sideEffects: None

  - name: clustermaintenancewindows.validators.supervisor.appscode.com
    clientConfig:
      service:
        namespace: default
        name: kubernetes
        path: /apis/clustermaintenancewindows.validators.supervisor.appscode.com/v1alpha1/clustermaintenancewindows
      caBundle: {{ b64enc .Values.apiserver.ca }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - supervisor.appscode.com
        apiVersions:
          - "*"
        resources:
          - clustermaintenancewindows
    admissionReviewVersions: ["v1beta1"]
    failurePolicy: Fail
    sideEffects: None
{{- end }}
