apiVersion: v1
kind: Service
metadata:
  name: {{ include "panopticon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panopticon.labels" . | nindent 4 }}
{{- if and (eq .Values.monitoring.agent "prometheus.io/builtin") .Values.monitoring.server }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
{{- end }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: 8443
  - name: api-self
    port: 8081
    targetPort: 8081
  selector:
    {{- include "panopticon.selectorLabels" . | nindent 4 }}


