{{- if and (eq .Values.monitoring.agent "prometheus.io/operator") .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "panopticon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.monitoring.serviceMonitor.labels }}
    {{- range $key, $val := .Values.monitoring.serviceMonitor.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
    {{- else }}
      {{- include "panopticon.selectorLabels" . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "panopticon.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: api
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    interval: 10s
    tlsConfig:
      ca:
        secret:
          name: {{ include "panopticon.fullname" . }}-apiserver-cert
          key: tls.crt
      serverName: "{{ include "panopticon.fullname" . }}.{{ .Release.Namespace }}.svc"
  - port: telemetry
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: http
    interval: 10s
{{- end }}
