{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.metrics.appscode.com
  labels:
    {{- include "panopticon.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
  - name: metricsconfigurations.validators.metrics.appscode.com
    clientConfig:
      service:
        namespace: default
        name: kubernetes
        path: /apis/validators.metrics.appscode.com/v1alpha1/metricsconfigurationvalidators
      caBundle: {{ b64enc .Values.apiserver.ca }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - metrics.appscode.com
        apiVersions:
          - "*"
        resources:
          - metricsconfigurations
    failurePolicy: Fail
    sideEffects: None
{{- end }}
