apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "petset.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "petset.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "petset.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "petset.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "petset.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "petset.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
