apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-connector.fullname" . }}-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-connector.labels" . | nindent 4 }}
type: Opaque
stringData:
  creds: {{ .Values.nats.creds | quote }}
