apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-connector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-connector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cluster-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cluster-connector.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "appscode.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "cluster-connector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.image.securityContext | nindent 12 }}
          image: {{ include "image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: PLATFORM_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "cluster-connector.fullname" . }}-token
                  key: token
          args:
            - run
            - --link-id={{ .Values.linkID | quote }}
            - --baseURL={{ .Values.platform.baseURL | quote }}
            - --token=$(PLATFORM_API_TOKEN)
            - --nats-addr={{ .Values.nats.address | quote }}
            - --license-file=/var/run/secrets/appscode/license/key.txt
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          volumeMounts:
            - mountPath: /var/run/secrets/appscode/license
              name: license
          resources:
            {{- toYaml .Values.image.resources | nindent 12 }}
      volumes:
        - name: license
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
