{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-ui-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-ui-server.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-ui-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-ui-server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/apiregistration.yaml: {{ include (print $.Template.BasePath "/apiregistration.yaml") . | sha256sum }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "appscode.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "kube-ui-server.serviceAccountName" . }}
      containers:
      - name: server
        securityContext:
          {{- toYaml .Values.image.securityContext | nindent 10 }}
        image: {{ include "image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy  }}
        args:
        - run
        - --v={{ .Values.logLevel }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --use-kubeapiserver-fqdn-for-aks={{ .Values.apiserver.useKubeapiserverFqdnForAks }}
    {{- with .Values.prometheus }}
      {{- with .address }}
        - --prometheus.address={{ . }}
      {{- end }}
      {{- with .basicAuth.username }}
        - --prometheus.basic-auth-username={{ . }}
      {{- end }}
      {{- if .basicAuth.password }}
        - --prometheus.basic-auth-password-file=/var/run/secrets/prometheus/auth/password
      {{- end }}
      {{- if .bearerToken }}
        - --prometheus.bearer-token-file=/var/run/secrets/prometheus/auth/token
      {{- end }}
      {{- if .proxyURL }}
        - --prometheus.proxy-url={{ .proxyURL }}
      {{- end }}
      {{- if .tls.ca }}
        - --prometheus.ca-cert-file=/var/run/secrets/prometheus/tls/ca.crt
      {{- end }}
      {{- if .tls.cert }}
        - --prometheus.client-cert-file=/var/run/secrets/prometheus/tls/client.crt
      {{- end }}
      {{- if .tls.key }}
        - --prometheus.client-key-file=/var/run/secrets/prometheus/tls/client.key
      {{- end }}
      {{- with .tls.serverName }}
        - --prometheus.server-name={{ . }}
      {{- end }}
      {{- with .tls.insecureSkipTLSVerify }}
        - --prometheus.insecure-skip-verify={{ . }}
      {{- end }}
    {{- end }}
        ports:
        - containerPort: 8443
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      {{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
      {{- end }}
        resources:
          {{- toYaml .Values.image.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
        - mountPath: /tmp
          name: tmp-dir
      {{- if or .Values.prometheus.basicAuth.password .Values.prometheus.bearerToken }}
        - mountPath: /var/run/secrets/prometheus/auth
          name: prometheus-auth
      {{- end }}
      {{- if .Values.prometheus.tls.ca }}
        - mountPath: /var/run/secrets/prometheus/tls
          name: prometheus-tls
      {{- end }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ include "kube-ui-server.fullname" . }}-apiserver-cert
      - name: tmp-dir
        emptyDir: {}
      {{- if or .Values.prometheus.basicAuth.password .Values.prometheus.bearerToken }}
      - name: prometheus-auth
        secret:
          defaultMode: 420
          secretName: {{ include "kube-ui-server.fullname" . }}-prometheus-auth
      {{- end }}
      {{- if .Values.prometheus.tls.ca }}
      - name: prometheus-tls
        secret:
          defaultMode: 420
          secretName: {{ include "kube-ui-server.fullname" . }}-prometheus-tls
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if or .Values.tolerations $criticalAddon }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end -}}
