{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-ui-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-ui-server.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-ui-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-ui-server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/apiregistration.yaml: {{ include (print $.Template.BasePath "/apiregistration.yaml") . | sha256sum }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kube-ui-server.serviceAccountName" . }}
      containers:
      - name: operator
        securityContext:
          {{- toYaml .Values.image.securityContext | nindent 10 }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy  }}
        args:
        - run
        - --v={{ .Values.logLevel }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --use-kubeapiserver-fqdn-for-aks={{ .Values.apiserver.useKubeapiserverFqdnForAks }}
    {{- with .Values.prometheus }}
      {{- if .address }}
        - --prometheus.address={{ .address }}
      {{- end }}
      {{- if .basicAuth.username }}
        - --prometheus.basic-auth-username={{ .basicAuth.username }}
      {{- end }}
      {{- if .basicAuth.password }}
        - --prometheus.basic-auth-password={{ .basicAuth.password }}
      {{- end }}
      {{- if .basicAuth.passwordFile }}
        - --prometheus.basic-auth-password-file={{ .basicAuth.passwordFile }}
      {{- end }}
      {{- if .bearerToken }}
        - --prometheus.bearer-token={{ .bearerToken }}
      {{- end }}
      {{- if .bearerTokenFile }}
        - --prometheus.bearer-token-file={{ .bearerTokenFile }}
      {{- end }}
      {{- if .proxyURL }}
        - --prometheus.proxy-url={{ .proxyURL }}
      {{- end }}
      {{- if .tlsConfig.caFile }}
        - --prometheus.ca-cert-file={{ .tlsConfig.caFile }}
      {{- end }}
      {{- if .tlsConfig.certFile }}
        - --prometheus.client-cert-file={{ .tlsConfig.certFile }}
      {{- end }}
      {{- if .tlsConfig.keyFile }}
        - --prometheus.client-key-file={{ .tlsConfig.keyFile }}
      {{- end }}
      {{- if .tlsConfig.serverName }}
        - --prometheus.server-name={{ .tlsConfig.serverName }}
      {{- end }}
      {{- if .tlsConfig.insecureSkipVerify }}
        - --prometheus.insecure-skip-verify={{ .tlsConfig.insecureSkipVerify }}
      {{- end }}
    {{- end }}
        ports:
        - containerPort: 8443
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      {{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
      {{- end }}
        resources:
          {{- toYaml .Values.image.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ include "kube-ui-server.fullname" . }}-apiserver-cert
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if or .Values.tolerations $criticalAddon }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end -}}
