{{ $data := dict }}

{{- if .Values.platform.token }}
{{ $_ := set $data "token" .Values.platform.token }}
{{- end }}

{{- if .Values.platform.caBundle }}
{{ $_ := set $data "ca.crt" .Values.platform.caBundle }}
{{- end }}

{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-ui-server.fullname" . }}-platform-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-ui-server.labels" . | nindent 4 }}
type: Opaque
stringData: {{ $data | toJson }}
{{- end }}
