apiVersion: v1
description: 'Config Syncer by AppsCode'
name: config-syncer
version: 0.14.3
appVersion: v0.14.1
home: https://github.com/kubeops/config-syncer
icon: https://cdn.appscode.com/images/products/kubed/icons/android-icon-192x192.png
sources:
  - https://github.com/kubeops/config-syncer
maintainers:
  - name: appscode
    email: support@appscode.com
